version: "3.1"
name: citybike-backend
services:
  postgres:
    build:
      context: ./postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: postgres
      POSTGRES_DB: citybike
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
  api:
    build:
      context: ./api
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - postgres
    develop:
      watch:
        - action: rebuild
          path: ./api/src
          target: /api/src
          ignore:
            - node_modules/
